### ISSUE TITLE
Future of library

### ISSUE THREAD

**Issue by BuFran** [Robotics-BUT/RoboUtils#2]
Ahoj Matouši,

  Rád bych zařadil tuto knihovnu do výuky naplno letošní rok, dostal jsem se konečně ní a vypadá dobře. 
  Potřebuji v ní ale dělat změny. Jaký zvolíme workflow ?

Varianty:

  * [ ]   Budeš ji managovat plně Ty
      *  Já si udělám fork
      *  Studenti stahují z tvého originálu
      *  Každou modifikaci pošlu jako pull reqest z mého orku
  * [ ]  Budu ji managovat já
      * Já si udělám fork
      * Studenti stahují z mého forku
      * Modifkace ti semtam pošlu a bude záležet na tobě jestli je integruješ
  * [ ] Jiný postup
      * prosím navrhni

Dík franta

**Comment by matoushybl** [comment]
This repository has been moved to the Robotics-BUT organisation and anyone in the core team should be able to manage it, without any reliance on my input.
